"""Add is_admin_reply column to ChatMessage

Revision ID: 9be4e90698da
Revises: d33d697a3fc1
Create Date: 2025-05-28 20:55:28.307206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be4e90698da'
down_revision = 'd33d697a3fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin_reply', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivered', sa.Boolean(), nullable=True))
        batch_op.alter_column('sender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('delivered')
        batch_op.drop_column('is_admin_reply')

    # ### end Alembic commands ###
